"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os
from setuptools import setup

APP_NAME = 'stockcharm'
driverDir = os.path.join(os.path.dirname(__file__), 'driver')

APP = ['ui_window.py']
DATA_FILES = [driverDir]
OPTIONS = {
    'argv_emulation': True,
}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
